language: java

matrix:
  include:
  - os: linux
    dist: trusty
    jdk: openjdk11
    env:
      - JDK_HOME=~/openjdk11 # force launching JLS using JDK11
  - os: osx
    osx_image: xcode10.1
    jdk: oraclejdk11

script: 
  - ./mvnw clean verify
  - ./mvnw checkstyle:check

cache:
  directories:
  - $HOME/.m2
